[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.10.0"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PRIVATE_STANDALONE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"


